stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Installing dependencies..."
    - npm install

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm test

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - npm run deploy
