name: Auto-Update Docs

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Generate Documentation
        run: python generate_docs.py
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "gajjarviren13@github.com"
          git add README.md
          git commit -m "Auto-update documentation"
          git push
